# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Deploying Application

on:
  push: # the push: ensures the workflow is executed for both push or closing of a pull request to the specified branch
    branches: [ "master" ] #you can change the branch name to your preferred branch e.g :"deploy"
  #pull_request: # the pull_request: ensures the workflow is executed when a pull request is opened on the specified branch
    #branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted
    strategy:
      matrix:
        node-version: [22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    #- run: cp .env.example .env
    - run: rm -rf node_modules/
    - run: npm i
    - run: npm run build --if-present
    - run: cp -r /home/debian/git-runners/_work/board/board/dist/. /var/www/pyratt.sh #copies contents of the build/dist folder to the '/var/www/web-app-name' folder where it will be served up
